name: Build and push by PR

on:
  pull_request:
    types: [ labeled ]
  push:
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.labels.*.name == 'deploy'
      || github.event_name == 'workflow_dispatch'
      || github.event_name == 'push'
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build the app
        run: |
          go mod tidy
          go build -o ./app ./cmd/main.go

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker europe-west10-docker.pkg.dev

      - name: Build and push Docker image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          SHORT_SHA=$(git rev-parse --short=7 ${{ github.sha }})
          IMAGE_NAME=europe-west10-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/blog-registry/blog:$SHORT_SHA
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Output the image name
        run: echo "Pushed Docker image $IMAGE_NAME"